// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: vcs/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_User    UserType = 0
	UserType_Bot     UserType = 1
	UserType_System  UserType = 2
	UserType_Machine UserType = 3
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "User",
		1: "Bot",
		2: "System",
		3: "Machine",
	}
	UserType_value = map[string]int32{
		"User":    0,
		"Bot":     1,
		"System":  2,
		"Machine": 3,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_vcs_common_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_vcs_common_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_vcs_common_proto_rawDescGZIP(), []int{0}
}

type ExtendedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedData) Reset() {
	*x = ExtendedData{}
	mi := &file_vcs_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedData) ProtoMessage() {}

func (x *ExtendedData) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedData.ProtoReflect.Descriptor instead.
func (*ExtendedData) Descriptor() ([]byte, []int) {
	return file_vcs_common_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendedData) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Author struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username    string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// email or login
	Email         *string   `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	AvatarUrl     *string   `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	ProfilWebUrl  *string   `protobuf:"bytes,6,opt,name=profil_web_url,json=profilWebUrl,proto3,oneof" json:"profil_web_url,omitempty"`
	State         *string   `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Type          *UserType `protobuf:"varint,8,opt,name=type,proto3,enum=vcs.common.v1.UserType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_vcs_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_vcs_common_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Author) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Author) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Author) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *Author) GetProfilWebUrl() string {
	if x != nil && x.ProfilWebUrl != nil {
		return *x.ProfilWebUrl
	}
	return ""
}

func (x *Author) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Author) GetType() UserType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return UserType_User
}

type HttpResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      *string                `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3,oneof" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponseMetadata) Reset() {
	*x = HttpResponseMetadata{}
	mi := &file_vcs_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseMetadata) ProtoMessage() {}

func (x *HttpResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseMetadata.ProtoReflect.Descriptor instead.
func (*HttpResponseMetadata) Descriptor() ([]byte, []int) {
	return file_vcs_common_proto_rawDescGZIP(), []int{2}
}

func (x *HttpResponseMetadata) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponseMetadata) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

var File_vcs_common_proto protoreflect.FileDescriptor

const file_vcs_common_proto_rawDesc = "" +
	"\n" +
	"\x10vcs/common.proto\x12\rvcs.common.v1\x1a\x1cgoogle/protobuf/struct.proto\";\n" +
	"\fExtendedData\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xcd\x02\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12)\n" +
	"\x0eprofil_web_url\x18\x06 \x01(\tH\x02R\fprofilWebUrl\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x03R\x05state\x88\x01\x01\x120\n" +
	"\x04type\x18\b \x01(\x0e2\x17.vcs.common.v1.UserTypeH\x04R\x04type\x88\x01\x01B\b\n" +
	"\x06_emailB\r\n" +
	"\v_avatar_urlB\x11\n" +
	"\x0f_profil_web_urlB\b\n" +
	"\x06_stateB\a\n" +
	"\x05_type\"^\n" +
	"\x14HttpResponseMetadata\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12 \n" +
	"\terror_msg\x18\x02 \x01(\tH\x00R\berrorMsg\x88\x01\x01B\f\n" +
	"\n" +
	"_error_msg*6\n" +
	"\bUserType\x12\b\n" +
	"\x04User\x10\x00\x12\a\n" +
	"\x03Bot\x10\x01\x12\n" +
	"\n" +
	"\x06System\x10\x02\x12\v\n" +
	"\aMachine\x10\x03B:Z8github.com/nivekalara237/ci-bridge-plugin-sdk/vcs/commonb\x06proto3"

var (
	file_vcs_common_proto_rawDescOnce sync.Once
	file_vcs_common_proto_rawDescData []byte
)

func file_vcs_common_proto_rawDescGZIP() []byte {
	file_vcs_common_proto_rawDescOnce.Do(func() {
		file_vcs_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vcs_common_proto_rawDesc), len(file_vcs_common_proto_rawDesc)))
	})
	return file_vcs_common_proto_rawDescData
}

var file_vcs_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vcs_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vcs_common_proto_goTypes = []any{
	(UserType)(0),                // 0: vcs.common.v1.UserType
	(*ExtendedData)(nil),         // 1: vcs.common.v1.ExtendedData
	(*Author)(nil),               // 2: vcs.common.v1.Author
	(*HttpResponseMetadata)(nil), // 3: vcs.common.v1.HttpResponseMetadata
	(*structpb.Struct)(nil),      // 4: google.protobuf.Struct
}
var file_vcs_common_proto_depIdxs = []int32{
	4, // 0: vcs.common.v1.ExtendedData.data:type_name -> google.protobuf.Struct
	0, // 1: vcs.common.v1.Author.type:type_name -> vcs.common.v1.UserType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vcs_common_proto_init() }
func file_vcs_common_proto_init() {
	if File_vcs_common_proto != nil {
		return
	}
	file_vcs_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_vcs_common_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vcs_common_proto_rawDesc), len(file_vcs_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vcs_common_proto_goTypes,
		DependencyIndexes: file_vcs_common_proto_depIdxs,
		EnumInfos:         file_vcs_common_proto_enumTypes,
		MessageInfos:      file_vcs_common_proto_msgTypes,
	}.Build()
	File_vcs_common_proto = out.File
	file_vcs_common_proto_goTypes = nil
	file_vcs_common_proto_depIdxs = nil
}
