// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: plugin/v1/handshake.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginInfo_GetInfo_FullMethodName = "/plugin.v1.PluginInfo/GetInfo"
)

// PluginInfoClient is the client API for PluginInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginInfo is the business handshake every sonarbridge plugin must
// implement, whatever its type (vcs, ...). It is called right after the
// go-plugin transport handshake succeeds, and its result is what the
// host validates before accepting the plugin as READY.
type PluginInfoClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type pluginInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginInfoClient(cc grpc.ClientConnInterface) PluginInfoClient {
	return &pluginInfoClient{cc}
}

func (c *pluginInfoClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, PluginInfo_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginInfoServer is the server API for PluginInfo service.
// All implementations must embed UnimplementedPluginInfoServer
// for forward compatibility.
//
// PluginInfo is the business handshake every sonarbridge plugin must
// implement, whatever its type (vcs, ...). It is called right after the
// go-plugin transport handshake succeeds, and its result is what the
// host validates before accepting the plugin as READY.
type PluginInfoServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedPluginInfoServer()
}

// UnimplementedPluginInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginInfoServer struct{}

func (UnimplementedPluginInfoServer) GetInfo(context.Context, *GetInfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginInfoServer) mustEmbedUnimplementedPluginInfoServer() {}
func (UnimplementedPluginInfoServer) testEmbeddedByValue()                    {}

// UnsafePluginInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginInfoServer will
// result in compilation errors.
type UnsafePluginInfoServer interface {
	mustEmbedUnimplementedPluginInfoServer()
}

func RegisterPluginInfoServer(s grpc.ServiceRegistrar, srv PluginInfoServer) {
	// If the following call panics, it indicates UnimplementedPluginInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginInfo_ServiceDesc, srv)
}

func _PluginInfo_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginInfoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginInfo_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginInfoServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginInfo_ServiceDesc is the grpc.ServiceDesc for PluginInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginInfo",
	HandlerType: (*PluginInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginInfo_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/handshake.proto",
}
