// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: plugin/v1/handshake.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_plugin_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_handshake_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PluginType      string                 `protobuf:"bytes,3,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_plugin_v1_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *InfoResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *InfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_plugin_v1_handshake_proto protoreflect.FileDescriptor

const file_plugin_v1_handshake_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/v1/handshake.proto\x12\tplugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\xac\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vplugin_type\x18\x03 \x01(\tR\n" +
	"pluginType\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\x05R\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities2K\n" +
	"\n" +
	"PluginInfo\x12=\n" +
	"\aGetInfo\x12\x19.plugin.v1.GetInfoRequest\x1a\x17.plugin.v1.InfoResponseB9Z7github.com/nivekalara237/ci-bridge-plugin-sdk/plugin/v1b\x06proto3"

var (
	file_plugin_v1_handshake_proto_rawDescOnce sync.Once
	file_plugin_v1_handshake_proto_rawDescData []byte
)

func file_plugin_v1_handshake_proto_rawDescGZIP() []byte {
	file_plugin_v1_handshake_proto_rawDescOnce.Do(func() {
		file_plugin_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_handshake_proto_rawDesc), len(file_plugin_v1_handshake_proto_rawDesc)))
	})
	return file_plugin_v1_handshake_proto_rawDescData
}

var file_plugin_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_v1_handshake_proto_goTypes = []any{
	(*GetInfoRequest)(nil), // 0: plugin.v1.GetInfoRequest
	(*InfoResponse)(nil),   // 1: plugin.v1.InfoResponse
}
var file_plugin_v1_handshake_proto_depIdxs = []int32{
	0, // 0: plugin.v1.PluginInfo.GetInfo:input_type -> plugin.v1.GetInfoRequest
	1, // 1: plugin.v1.PluginInfo.GetInfo:output_type -> plugin.v1.InfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_v1_handshake_proto_init() }
func file_plugin_v1_handshake_proto_init() {
	if File_plugin_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_handshake_proto_rawDesc), len(file_plugin_v1_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_handshake_proto_goTypes,
		DependencyIndexes: file_plugin_v1_handshake_proto_depIdxs,
		MessageInfos:      file_plugin_v1_handshake_proto_msgTypes,
	}.Build()
	File_plugin_v1_handshake_proto = out.File
	file_plugin_v1_handshake_proto_goTypes = nil
	file_plugin_v1_handshake_proto_depIdxs = nil
}
