// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: vcs/comment_note.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentAndNoteService_CreatePullrequestCommentOrNote_FullMethodName = "/vcs.comment.v1.CommentAndNoteService/CreatePullrequestCommentOrNote"
	CommentAndNoteService_UpdatePullrequestComment_FullMethodName       = "/vcs.comment.v1.CommentAndNoteService/UpdatePullrequestComment"
	CommentAndNoteService_DeletePullrequestComment_FullMethodName       = "/vcs.comment.v1.CommentAndNoteService/DeletePullrequestComment"
)

// CommentAndNoteServiceClient is the client API for CommentAndNoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentAndNoteServiceClient interface {
	CreatePullrequestCommentOrNote(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateOrUpdateCommentResponse, error)
	UpdatePullrequestComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*CreateOrUpdateCommentResponse, error)
	DeletePullrequestComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type commentAndNoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentAndNoteServiceClient(cc grpc.ClientConnInterface) CommentAndNoteServiceClient {
	return &commentAndNoteServiceClient{cc}
}

func (c *commentAndNoteServiceClient) CreatePullrequestCommentOrNote(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateOrUpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateCommentResponse)
	err := c.cc.Invoke(ctx, CommentAndNoteService_CreatePullrequestCommentOrNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentAndNoteServiceClient) UpdatePullrequestComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*CreateOrUpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateCommentResponse)
	err := c.cc.Invoke(ctx, CommentAndNoteService_UpdatePullrequestComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentAndNoteServiceClient) DeletePullrequestComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, CommentAndNoteService_DeletePullrequestComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentAndNoteServiceServer is the server API for CommentAndNoteService service.
// All implementations must embed UnimplementedCommentAndNoteServiceServer
// for forward compatibility.
type CommentAndNoteServiceServer interface {
	CreatePullrequestCommentOrNote(context.Context, *CreateCommentRequest) (*CreateOrUpdateCommentResponse, error)
	UpdatePullrequestComment(context.Context, *UpdateCommentRequest) (*CreateOrUpdateCommentResponse, error)
	DeletePullrequestComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedCommentAndNoteServiceServer()
}

// UnimplementedCommentAndNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentAndNoteServiceServer struct{}

func (UnimplementedCommentAndNoteServiceServer) CreatePullrequestCommentOrNote(context.Context, *CreateCommentRequest) (*CreateOrUpdateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePullrequestCommentOrNote not implemented")
}
func (UnimplementedCommentAndNoteServiceServer) UpdatePullrequestComment(context.Context, *UpdateCommentRequest) (*CreateOrUpdateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePullrequestComment not implemented")
}
func (UnimplementedCommentAndNoteServiceServer) DeletePullrequestComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePullrequestComment not implemented")
}
func (UnimplementedCommentAndNoteServiceServer) mustEmbedUnimplementedCommentAndNoteServiceServer() {}
func (UnimplementedCommentAndNoteServiceServer) testEmbeddedByValue()                               {}

// UnsafeCommentAndNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentAndNoteServiceServer will
// result in compilation errors.
type UnsafeCommentAndNoteServiceServer interface {
	mustEmbedUnimplementedCommentAndNoteServiceServer()
}

func RegisterCommentAndNoteServiceServer(s grpc.ServiceRegistrar, srv CommentAndNoteServiceServer) {
	// If the following call panics, it indicates UnimplementedCommentAndNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentAndNoteService_ServiceDesc, srv)
}

func _CommentAndNoteService_CreatePullrequestCommentOrNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentAndNoteServiceServer).CreatePullrequestCommentOrNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentAndNoteService_CreatePullrequestCommentOrNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentAndNoteServiceServer).CreatePullrequestCommentOrNote(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentAndNoteService_UpdatePullrequestComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentAndNoteServiceServer).UpdatePullrequestComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentAndNoteService_UpdatePullrequestComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentAndNoteServiceServer).UpdatePullrequestComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentAndNoteService_DeletePullrequestComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentAndNoteServiceServer).DeletePullrequestComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentAndNoteService_DeletePullrequestComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentAndNoteServiceServer).DeletePullrequestComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentAndNoteService_ServiceDesc is the grpc.ServiceDesc for CommentAndNoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentAndNoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vcs.comment.v1.CommentAndNoteService",
	HandlerType: (*CommentAndNoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePullrequestCommentOrNote",
			Handler:    _CommentAndNoteService_CreatePullrequestCommentOrNote_Handler,
		},
		{
			MethodName: "UpdatePullrequestComment",
			Handler:    _CommentAndNoteService_UpdatePullrequestComment_Handler,
		},
		{
			MethodName: "DeletePullrequestComment",
			Handler:    _CommentAndNoteService_DeletePullrequestComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vcs/comment_note.proto",
}
