// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: vcs/comment_note.proto

package comment

import (
	common "github.com/nivekalara237/ci-bridge-plugin-sdk/vcs/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Gitlab: mr_iid, Github: issue_number
	PullrequestId string                 `protobuf:"bytes,2,opt,name=pullrequest_id,json=pullrequestId,proto3" json:"pullrequest_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Others        *common.AdditionalData `protobuf:"bytes,5,opt,name=others,proto3,oneof" json:"others,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_vcs_comment_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateCommentRequest) GetPullrequestId() string {
	if x != nil {
		return x.PullrequestId
	}
	return ""
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateCommentRequest) GetOthers() *common.AdditionalData {
	if x != nil {
		return x.Others
	}
	return nil
}

type UpdateCommentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Gitlab: mr_iid, Github: issue_number
	PullrequestId string                 `protobuf:"bytes,2,opt,name=pullrequest_id,json=pullrequestId,proto3" json:"pullrequest_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CommentId     string                 `protobuf:"bytes,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Others        *common.AdditionalData `protobuf:"bytes,5,opt,name=others,proto3,oneof" json:"others,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_vcs_comment_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCommentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateCommentRequest) GetPullrequestId() string {
	if x != nil {
		return x.PullrequestId
	}
	return ""
}

func (x *UpdateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentRequest) GetOthers() *common.AdditionalData {
	if x != nil {
		return x.Others
	}
	return nil
}

type DeleteCommentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Gitlab: mr_iid, Github: issue_number
	PullrequestId string `protobuf:"bytes,2,opt,name=pullrequest_id,json=pullrequestId,proto3" json:"pullrequest_id,omitempty"`
	CommentId     string `protobuf:"bytes,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_vcs_comment_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCommentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteCommentRequest) GetPullrequestId() string {
	if x != nil {
		return x.PullrequestId
	}
	return ""
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type CommentItemResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body            string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	System          *bool                  `protobuf:"varint,5,opt,name=system,proto3,oneof" json:"system,omitempty"`
	NoteOrCommentId *string                `protobuf:"bytes,6,opt,name=note_or_comment_id,json=noteOrCommentId,proto3,oneof" json:"note_or_comment_id,omitempty"`
	NoteUrl         *string                `protobuf:"bytes,7,opt,name=note_url,json=noteUrl,proto3,oneof" json:"note_url,omitempty"`
	Author          *common.Author         `protobuf:"bytes,8,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Others          *common.AdditionalData `protobuf:"bytes,9,opt,name=others,proto3,oneof" json:"others,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommentItemResponse) Reset() {
	*x = CommentItemResponse{}
	mi := &file_vcs_comment_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItemResponse) ProtoMessage() {}

func (x *CommentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItemResponse.ProtoReflect.Descriptor instead.
func (*CommentItemResponse) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{3}
}

func (x *CommentItemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentItemResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CommentItemResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentItemResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CommentItemResponse) GetSystem() bool {
	if x != nil && x.System != nil {
		return *x.System
	}
	return false
}

func (x *CommentItemResponse) GetNoteOrCommentId() string {
	if x != nil && x.NoteOrCommentId != nil {
		return *x.NoteOrCommentId
	}
	return ""
}

func (x *CommentItemResponse) GetNoteUrl() string {
	if x != nil && x.NoteUrl != nil {
		return *x.NoteUrl
	}
	return ""
}

func (x *CommentItemResponse) GetAuthor() *common.Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *CommentItemResponse) GetOthers() *common.AdditionalData {
	if x != nil {
		return x.Others
	}
	return nil
}

type CreateOrUpdateCommentResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Metadata      *common.HttpResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data          *CommentItemResponse         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateCommentResponse) Reset() {
	*x = CreateOrUpdateCommentResponse{}
	mi := &file_vcs_comment_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateCommentResponse) ProtoMessage() {}

func (x *CreateOrUpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrUpdateCommentResponse) GetMetadata() *common.HttpResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateOrUpdateCommentResponse) GetData() *CommentItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Metadata      *common.HttpResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_vcs_comment_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_comment_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_vcs_comment_note_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentResponse) GetMetadata() *common.HttpResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_vcs_comment_note_proto protoreflect.FileDescriptor

const file_vcs_comment_note_proto_rawDesc = "" +
	"\n" +
	"\x16vcs/comment_note.proto\x12\x0evcs.comment.v1\x1a\x10vcs/common.proto\"\xb7\x01\n" +
	"\x14CreateCommentRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12%\n" +
	"\x0epullrequest_id\x18\x02 \x01(\tR\rpullrequestId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12:\n" +
	"\x06others\x18\x05 \x01(\v2\x1d.vcs.common.v1.AdditionalDataH\x00R\x06others\x88\x01\x01B\t\n" +
	"\a_others\"\xd6\x01\n" +
	"\x14UpdateCommentRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12%\n" +
	"\x0epullrequest_id\x18\x02 \x01(\tR\rpullrequestId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\tR\tcommentId\x12:\n" +
	"\x06others\x18\x05 \x01(\v2\x1d.vcs.common.v1.AdditionalDataH\x00R\x06others\x88\x01\x01B\t\n" +
	"\a_others\"{\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12%\n" +
	"\x0epullrequest_id\x18\x02 \x01(\tR\rpullrequestId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\tR\tcommentId\"\x9b\x03\n" +
	"\x13CommentItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\x06system\x18\x05 \x01(\bH\x00R\x06system\x88\x01\x01\x120\n" +
	"\x12note_or_comment_id\x18\x06 \x01(\tH\x01R\x0fnoteOrCommentId\x88\x01\x01\x12\x1e\n" +
	"\bnote_url\x18\a \x01(\tH\x02R\anoteUrl\x88\x01\x01\x122\n" +
	"\x06author\x18\b \x01(\v2\x15.vcs.common.v1.AuthorH\x03R\x06author\x88\x01\x01\x12:\n" +
	"\x06others\x18\t \x01(\v2\x1d.vcs.common.v1.AdditionalDataH\x04R\x06others\x88\x01\x01B\t\n" +
	"\a_systemB\x15\n" +
	"\x13_note_or_comment_idB\v\n" +
	"\t_note_urlB\t\n" +
	"\a_authorB\t\n" +
	"\a_others\"\x99\x01\n" +
	"\x1dCreateOrUpdateCommentResponse\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2#.vcs.common.v1.HttpResponseMetadataR\bmetadata\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.vcs.comment.v1.CommentItemResponseR\x04data\"X\n" +
	"\x15DeleteCommentResponse\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2#.vcs.common.v1.HttpResponseMetadataR\bmetadata2\xe8\x02\n" +
	"\x15CommentAndNoteService\x12u\n" +
	"\x1eCreatePullrequestCommentOrNote\x12$.vcs.comment.v1.CreateCommentRequest\x1a-.vcs.comment.v1.CreateOrUpdateCommentResponse\x12o\n" +
	"\x18UpdatePullrequestComment\x12$.vcs.comment.v1.UpdateCommentRequest\x1a-.vcs.comment.v1.CreateOrUpdateCommentResponse\x12g\n" +
	"\x18DeletePullrequestComment\x12$.vcs.comment.v1.DeleteCommentRequest\x1a%.vcs.comment.v1.DeleteCommentResponseB;Z9github.com/nivekalara237/ci-bridge-plugin-sdk/vcs/commentb\x06proto3"

var (
	file_vcs_comment_note_proto_rawDescOnce sync.Once
	file_vcs_comment_note_proto_rawDescData []byte
)

func file_vcs_comment_note_proto_rawDescGZIP() []byte {
	file_vcs_comment_note_proto_rawDescOnce.Do(func() {
		file_vcs_comment_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vcs_comment_note_proto_rawDesc), len(file_vcs_comment_note_proto_rawDesc)))
	})
	return file_vcs_comment_note_proto_rawDescData
}

var file_vcs_comment_note_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vcs_comment_note_proto_goTypes = []any{
	(*CreateCommentRequest)(nil),          // 0: vcs.comment.v1.CreateCommentRequest
	(*UpdateCommentRequest)(nil),          // 1: vcs.comment.v1.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),          // 2: vcs.comment.v1.DeleteCommentRequest
	(*CommentItemResponse)(nil),           // 3: vcs.comment.v1.CommentItemResponse
	(*CreateOrUpdateCommentResponse)(nil), // 4: vcs.comment.v1.CreateOrUpdateCommentResponse
	(*DeleteCommentResponse)(nil),         // 5: vcs.comment.v1.DeleteCommentResponse
	(*common.AdditionalData)(nil),         // 6: vcs.common.v1.AdditionalData
	(*common.Author)(nil),                 // 7: vcs.common.v1.Author
	(*common.HttpResponseMetadata)(nil),   // 8: vcs.common.v1.HttpResponseMetadata
}
var file_vcs_comment_note_proto_depIdxs = []int32{
	6,  // 0: vcs.comment.v1.CreateCommentRequest.others:type_name -> vcs.common.v1.AdditionalData
	6,  // 1: vcs.comment.v1.UpdateCommentRequest.others:type_name -> vcs.common.v1.AdditionalData
	7,  // 2: vcs.comment.v1.CommentItemResponse.author:type_name -> vcs.common.v1.Author
	6,  // 3: vcs.comment.v1.CommentItemResponse.others:type_name -> vcs.common.v1.AdditionalData
	8,  // 4: vcs.comment.v1.CreateOrUpdateCommentResponse.metadata:type_name -> vcs.common.v1.HttpResponseMetadata
	3,  // 5: vcs.comment.v1.CreateOrUpdateCommentResponse.data:type_name -> vcs.comment.v1.CommentItemResponse
	8,  // 6: vcs.comment.v1.DeleteCommentResponse.metadata:type_name -> vcs.common.v1.HttpResponseMetadata
	0,  // 7: vcs.comment.v1.CommentAndNoteService.CreatePullrequestCommentOrNote:input_type -> vcs.comment.v1.CreateCommentRequest
	1,  // 8: vcs.comment.v1.CommentAndNoteService.UpdatePullrequestComment:input_type -> vcs.comment.v1.UpdateCommentRequest
	2,  // 9: vcs.comment.v1.CommentAndNoteService.DeletePullrequestComment:input_type -> vcs.comment.v1.DeleteCommentRequest
	4,  // 10: vcs.comment.v1.CommentAndNoteService.CreatePullrequestCommentOrNote:output_type -> vcs.comment.v1.CreateOrUpdateCommentResponse
	4,  // 11: vcs.comment.v1.CommentAndNoteService.UpdatePullrequestComment:output_type -> vcs.comment.v1.CreateOrUpdateCommentResponse
	5,  // 12: vcs.comment.v1.CommentAndNoteService.DeletePullrequestComment:output_type -> vcs.comment.v1.DeleteCommentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vcs_comment_note_proto_init() }
func file_vcs_comment_note_proto_init() {
	if File_vcs_comment_note_proto != nil {
		return
	}
	file_vcs_comment_note_proto_msgTypes[0].OneofWrappers = []any{}
	file_vcs_comment_note_proto_msgTypes[1].OneofWrappers = []any{}
	file_vcs_comment_note_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vcs_comment_note_proto_rawDesc), len(file_vcs_comment_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vcs_comment_note_proto_goTypes,
		DependencyIndexes: file_vcs_comment_note_proto_depIdxs,
		MessageInfos:      file_vcs_comment_note_proto_msgTypes,
	}.Build()
	File_vcs_comment_note_proto = out.File
	file_vcs_comment_note_proto_goTypes = nil
	file_vcs_comment_note_proto_depIdxs = nil
}
