// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: vcs/pull_request.proto

package pullrequest

import (
	common "github.com/nivekalara237/ci-bridge-plugin-sdk/vcs/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPullRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GitLab: ID/path ; GitHub: owner/repo ; BB: workspace/repo ; Gitea: owner/repo
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// GitLab: merge_request_iid ; GitHub: number ; BB: id ; Gitea: index
	PullrequestId string `protobuf:"bytes,2,opt,name=pullrequest_id,json=pullrequestId,proto3" json:"pullrequest_id,omitempty"`
	// only github and gitea
	Owner         *string                `protobuf:"bytes,3,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Data          *common.AdditionalData `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullRequestRequest) Reset() {
	*x = GetPullRequestRequest{}
	mi := &file_vcs_pull_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestRequest) ProtoMessage() {}

func (x *GetPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_pull_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestRequest.ProtoReflect.Descriptor instead.
func (*GetPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_vcs_pull_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetPullRequestRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetPullRequestRequest) GetPullrequestId() string {
	if x != nil {
		return x.PullrequestId
	}
	return ""
}

func (x *GetPullRequestRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *GetPullRequestRequest) GetData() *common.AdditionalData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPullRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// gitlab: iid; github: number; bb:
	PrIid string `protobuf:"bytes,2,opt,name=pr_iid,json=prIid,proto3" json:"pr_iid,omitempty"`
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// github: body, bb: rendered
	Description        string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	State              string           `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt          string           `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string           `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TargetBranch       string           `protobuf:"bytes,8,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	SourceBranch       string           `protobuf:"bytes,9,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	ClosedAt           string           `protobuf:"bytes,10,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	ClosedBy           *common.Author   `protobuf:"bytes,11,opt,name=closed_by,json=closedBy,proto3,oneof" json:"closed_by,omitempty"`
	MergedAt           *string          `protobuf:"bytes,12,opt,name=merged_at,json=mergedAt,proto3,oneof" json:"merged_at,omitempty"`
	MergedBy           *common.Author   `protobuf:"bytes,13,opt,name=merged_by,json=mergedBy,proto3,oneof" json:"merged_by,omitempty"`
	CommentCount       int32            `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ReviewCommentCount int32            `protobuf:"varint,15,opt,name=review_comment_count,json=reviewCommentCount,proto3" json:"review_comment_count,omitempty"`
	CommitCount        int32            `protobuf:"varint,16,opt,name=commit_count,json=commitCount,proto3" json:"commit_count,omitempty"`
	ChangedFilesCount  int32            `protobuf:"varint,17,opt,name=changed_files_count,json=changedFilesCount,proto3" json:"changed_files_count,omitempty"`
	Mergeable          bool             `protobuf:"varint,18,opt,name=mergeable,proto3" json:"mergeable,omitempty"`
	Rebaseable         bool             `protobuf:"varint,19,opt,name=rebaseable,proto3" json:"rebaseable,omitempty"`
	Merged             bool             `protobuf:"varint,20,opt,name=merged,proto3" json:"merged,omitempty"`
	Author             *common.Author   `protobuf:"bytes,21,opt,name=author,proto3" json:"author,omitempty"`
	AssignedTo         *common.Author   `protobuf:"bytes,22,opt,name=assigned_to,json=assignedTo,proto3,oneof" json:"assigned_to,omitempty"`
	Assignees          []*common.Author `protobuf:"bytes,23,rep,name=assignees,proto3" json:"assignees,omitempty"`
	Draft              bool             `protobuf:"varint,24,opt,name=draft,proto3" json:"draft,omitempty"`
	Sha                *string          `protobuf:"bytes,25,opt,name=sha,proto3,oneof" json:"sha,omitempty"`
	RequestedReviews   []*common.Author `protobuf:"bytes,26,rep,name=requested_reviews,json=requestedReviews,proto3" json:"requested_reviews,omitempty"`
	WebUrl             *string          `protobuf:"bytes,27,opt,name=web_url,json=webUrl,proto3,oneof" json:"web_url,omitempty"`
	Approved           bool             `protobuf:"varint,28,opt,name=approved,proto3" json:"approved,omitempty"`
	ApprovedBy         *common.Author   `protobuf:"bytes,29,opt,name=approved_by,json=approvedBy,proto3,oneof" json:"approved_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPullRequestResponse) Reset() {
	*x = GetPullRequestResponse{}
	mi := &file_vcs_pull_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestResponse) ProtoMessage() {}

func (x *GetPullRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_pull_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestResponse.ProtoReflect.Descriptor instead.
func (*GetPullRequestResponse) Descriptor() ([]byte, []int) {
	return file_vcs_pull_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetPullRequestResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPullRequestResponse) GetPrIid() string {
	if x != nil {
		return x.PrIid
	}
	return ""
}

func (x *GetPullRequestResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPullRequestResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetPullRequestResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetPullRequestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetPullRequestResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetPullRequestResponse) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *GetPullRequestResponse) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *GetPullRequestResponse) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *GetPullRequestResponse) GetClosedBy() *common.Author {
	if x != nil {
		return x.ClosedBy
	}
	return nil
}

func (x *GetPullRequestResponse) GetMergedAt() string {
	if x != nil && x.MergedAt != nil {
		return *x.MergedAt
	}
	return ""
}

func (x *GetPullRequestResponse) GetMergedBy() *common.Author {
	if x != nil {
		return x.MergedBy
	}
	return nil
}

func (x *GetPullRequestResponse) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetPullRequestResponse) GetReviewCommentCount() int32 {
	if x != nil {
		return x.ReviewCommentCount
	}
	return 0
}

func (x *GetPullRequestResponse) GetCommitCount() int32 {
	if x != nil {
		return x.CommitCount
	}
	return 0
}

func (x *GetPullRequestResponse) GetChangedFilesCount() int32 {
	if x != nil {
		return x.ChangedFilesCount
	}
	return 0
}

func (x *GetPullRequestResponse) GetMergeable() bool {
	if x != nil {
		return x.Mergeable
	}
	return false
}

func (x *GetPullRequestResponse) GetRebaseable() bool {
	if x != nil {
		return x.Rebaseable
	}
	return false
}

func (x *GetPullRequestResponse) GetMerged() bool {
	if x != nil {
		return x.Merged
	}
	return false
}

func (x *GetPullRequestResponse) GetAuthor() *common.Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *GetPullRequestResponse) GetAssignedTo() *common.Author {
	if x != nil {
		return x.AssignedTo
	}
	return nil
}

func (x *GetPullRequestResponse) GetAssignees() []*common.Author {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *GetPullRequestResponse) GetDraft() bool {
	if x != nil {
		return x.Draft
	}
	return false
}

func (x *GetPullRequestResponse) GetSha() string {
	if x != nil && x.Sha != nil {
		return *x.Sha
	}
	return ""
}

func (x *GetPullRequestResponse) GetRequestedReviews() []*common.Author {
	if x != nil {
		return x.RequestedReviews
	}
	return nil
}

func (x *GetPullRequestResponse) GetWebUrl() string {
	if x != nil && x.WebUrl != nil {
		return *x.WebUrl
	}
	return ""
}

func (x *GetPullRequestResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *GetPullRequestResponse) GetApprovedBy() *common.Author {
	if x != nil {
		return x.ApprovedBy
	}
	return nil
}

var File_vcs_pull_request_proto protoreflect.FileDescriptor

const file_vcs_pull_request_proto_rawDesc = "" +
	"\n" +
	"\x16vcs/pull_request.proto\x12\x12vcs.pullrequest.v1\x1a\x10vcs/common.proto\"\xc3\x01\n" +
	"\x15GetPullRequestRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12%\n" +
	"\x0epullrequest_id\x18\x02 \x01(\tR\rpullrequestId\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\tH\x00R\x05owner\x88\x01\x01\x126\n" +
	"\x04data\x18\x04 \x01(\v2\x1d.vcs.common.v1.AdditionalDataH\x01R\x04data\x88\x01\x01B\b\n" +
	"\x06_ownerB\a\n" +
	"\x05_data\"\xad\t\n" +
	"\x16GetPullRequestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06pr_iid\x18\x02 \x01(\tR\x05prIid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12#\n" +
	"\rtarget_branch\x18\b \x01(\tR\ftargetBranch\x12#\n" +
	"\rsource_branch\x18\t \x01(\tR\fsourceBranch\x12\x1b\n" +
	"\tclosed_at\x18\n" +
	" \x01(\tR\bclosedAt\x127\n" +
	"\tclosed_by\x18\v \x01(\v2\x15.vcs.common.v1.AuthorH\x00R\bclosedBy\x88\x01\x01\x12 \n" +
	"\tmerged_at\x18\f \x01(\tH\x01R\bmergedAt\x88\x01\x01\x127\n" +
	"\tmerged_by\x18\r \x01(\v2\x15.vcs.common.v1.AuthorH\x02R\bmergedBy\x88\x01\x01\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\x05R\fcommentCount\x120\n" +
	"\x14review_comment_count\x18\x0f \x01(\x05R\x12reviewCommentCount\x12!\n" +
	"\fcommit_count\x18\x10 \x01(\x05R\vcommitCount\x12.\n" +
	"\x13changed_files_count\x18\x11 \x01(\x05R\x11changedFilesCount\x12\x1c\n" +
	"\tmergeable\x18\x12 \x01(\bR\tmergeable\x12\x1e\n" +
	"\n" +
	"rebaseable\x18\x13 \x01(\bR\n" +
	"rebaseable\x12\x16\n" +
	"\x06merged\x18\x14 \x01(\bR\x06merged\x12-\n" +
	"\x06author\x18\x15 \x01(\v2\x15.vcs.common.v1.AuthorR\x06author\x12;\n" +
	"\vassigned_to\x18\x16 \x01(\v2\x15.vcs.common.v1.AuthorH\x03R\n" +
	"assignedTo\x88\x01\x01\x123\n" +
	"\tassignees\x18\x17 \x03(\v2\x15.vcs.common.v1.AuthorR\tassignees\x12\x14\n" +
	"\x05draft\x18\x18 \x01(\bR\x05draft\x12\x15\n" +
	"\x03sha\x18\x19 \x01(\tH\x04R\x03sha\x88\x01\x01\x12B\n" +
	"\x11requested_reviews\x18\x1a \x03(\v2\x15.vcs.common.v1.AuthorR\x10requestedReviews\x12\x1c\n" +
	"\aweb_url\x18\x1b \x01(\tH\x05R\x06webUrl\x88\x01\x01\x12\x1a\n" +
	"\bapproved\x18\x1c \x01(\bR\bapproved\x12;\n" +
	"\vapproved_by\x18\x1d \x01(\v2\x15.vcs.common.v1.AuthorH\x06R\n" +
	"approvedBy\x88\x01\x01B\f\n" +
	"\n" +
	"_closed_byB\f\n" +
	"\n" +
	"_merged_atB\f\n" +
	"\n" +
	"_merged_byB\x0e\n" +
	"\f_assigned_toB\x06\n" +
	"\x04_shaB\n" +
	"\n" +
	"\b_web_urlB\x0e\n" +
	"\f_approved_by2}\n" +
	"\x12PullRequestService\x12g\n" +
	"\x0eGetPullRequest\x12).vcs.pullrequest.v1.GetPullRequestRequest\x1a*.vcs.pullrequest.v1.GetPullRequestResponseB?Z=github.com/nivekalara237/ci-bridge-plugin-sdk/vcs/pullrequestb\x06proto3"

var (
	file_vcs_pull_request_proto_rawDescOnce sync.Once
	file_vcs_pull_request_proto_rawDescData []byte
)

func file_vcs_pull_request_proto_rawDescGZIP() []byte {
	file_vcs_pull_request_proto_rawDescOnce.Do(func() {
		file_vcs_pull_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vcs_pull_request_proto_rawDesc), len(file_vcs_pull_request_proto_rawDesc)))
	})
	return file_vcs_pull_request_proto_rawDescData
}

var file_vcs_pull_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vcs_pull_request_proto_goTypes = []any{
	(*GetPullRequestRequest)(nil),  // 0: vcs.pullrequest.v1.GetPullRequestRequest
	(*GetPullRequestResponse)(nil), // 1: vcs.pullrequest.v1.GetPullRequestResponse
	(*common.AdditionalData)(nil),  // 2: vcs.common.v1.AdditionalData
	(*common.Author)(nil),          // 3: vcs.common.v1.Author
}
var file_vcs_pull_request_proto_depIdxs = []int32{
	2, // 0: vcs.pullrequest.v1.GetPullRequestRequest.data:type_name -> vcs.common.v1.AdditionalData
	3, // 1: vcs.pullrequest.v1.GetPullRequestResponse.closed_by:type_name -> vcs.common.v1.Author
	3, // 2: vcs.pullrequest.v1.GetPullRequestResponse.merged_by:type_name -> vcs.common.v1.Author
	3, // 3: vcs.pullrequest.v1.GetPullRequestResponse.author:type_name -> vcs.common.v1.Author
	3, // 4: vcs.pullrequest.v1.GetPullRequestResponse.assigned_to:type_name -> vcs.common.v1.Author
	3, // 5: vcs.pullrequest.v1.GetPullRequestResponse.assignees:type_name -> vcs.common.v1.Author
	3, // 6: vcs.pullrequest.v1.GetPullRequestResponse.requested_reviews:type_name -> vcs.common.v1.Author
	3, // 7: vcs.pullrequest.v1.GetPullRequestResponse.approved_by:type_name -> vcs.common.v1.Author
	0, // 8: vcs.pullrequest.v1.PullRequestService.GetPullRequest:input_type -> vcs.pullrequest.v1.GetPullRequestRequest
	1, // 9: vcs.pullrequest.v1.PullRequestService.GetPullRequest:output_type -> vcs.pullrequest.v1.GetPullRequestResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_vcs_pull_request_proto_init() }
func file_vcs_pull_request_proto_init() {
	if File_vcs_pull_request_proto != nil {
		return
	}
	file_vcs_pull_request_proto_msgTypes[0].OneofWrappers = []any{}
	file_vcs_pull_request_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vcs_pull_request_proto_rawDesc), len(file_vcs_pull_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vcs_pull_request_proto_goTypes,
		DependencyIndexes: file_vcs_pull_request_proto_depIdxs,
		MessageInfos:      file_vcs_pull_request_proto_msgTypes,
	}.Build()
	File_vcs_pull_request_proto = out.File
	file_vcs_pull_request_proto_goTypes = nil
	file_vcs_pull_request_proto_depIdxs = nil
}
