// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: vcs/pull_request.proto

package pullrequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PullRequestService_GetPullRequest_FullMethodName = "/vcs.pullrequest.v1.PullRequestService/GetPullRequest"
)

// PullRequestServiceClient is the client API for PullRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PullRequestServiceClient interface {
	GetPullRequest(ctx context.Context, in *GetPullRequestRequest, opts ...grpc.CallOption) (*GetPullRequestResponse, error)
}

type pullRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPullRequestServiceClient(cc grpc.ClientConnInterface) PullRequestServiceClient {
	return &pullRequestServiceClient{cc}
}

func (c *pullRequestServiceClient) GetPullRequest(ctx context.Context, in *GetPullRequestRequest, opts ...grpc.CallOption) (*GetPullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestResponse)
	err := c.cc.Invoke(ctx, PullRequestService_GetPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PullRequestServiceServer is the server API for PullRequestService service.
// All implementations must embed UnimplementedPullRequestServiceServer
// for forward compatibility.
type PullRequestServiceServer interface {
	GetPullRequest(context.Context, *GetPullRequestRequest) (*GetPullRequestResponse, error)
	mustEmbedUnimplementedPullRequestServiceServer()
}

// UnimplementedPullRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPullRequestServiceServer struct{}

func (UnimplementedPullRequestServiceServer) GetPullRequest(context.Context, *GetPullRequestRequest) (*GetPullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequest not implemented")
}
func (UnimplementedPullRequestServiceServer) mustEmbedUnimplementedPullRequestServiceServer() {}
func (UnimplementedPullRequestServiceServer) testEmbeddedByValue()                            {}

// UnsafePullRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PullRequestServiceServer will
// result in compilation errors.
type UnsafePullRequestServiceServer interface {
	mustEmbedUnimplementedPullRequestServiceServer()
}

func RegisterPullRequestServiceServer(s grpc.ServiceRegistrar, srv PullRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedPullRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PullRequestService_ServiceDesc, srv)
}

func _PullRequestService_GetPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PullRequestServiceServer).GetPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PullRequestService_GetPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PullRequestServiceServer).GetPullRequest(ctx, req.(*GetPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PullRequestService_ServiceDesc is the grpc.ServiceDesc for PullRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PullRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vcs.pullrequest.v1.PullRequestService",
	HandlerType: (*PullRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPullRequest",
			Handler:    _PullRequestService_GetPullRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vcs/pull_request.proto",
}
